In [1]:
import torch
import numpy as np


In [2]:
torch.cuda.is_available()

True

In [3]:
mat_a = [
    [1,4,5], [2,7,9]
]
mat_a = torch.tensor(mat_a, dtype = torch.float32)
print(mat_a.dtype)
print(mat_a.shape)

torch.float32
torch.Size([2, 3])


In [4]:
print(mat_a)

tensor([[1., 4., 5.],
        [2., 7., 9.]])


In [5]:
numpy_matrix = np.array([
    [1,4,5], [2,7,9]
])
print(numpy_matrix.shape)
print(numpy_matrix.dtype)
tensor_matrix = torch.from_numpy(numpy_matrix)
print(tensor_matrix.shape)
print(tensor_matrix.dtype)

(2, 3)
int64
torch.Size([2, 3])
torch.int64


In [6]:
x_zeros = torch.zeros((3,3),dtype= torch.int64)

In [7]:
x_zeros

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.rand(2,3)

tensor([[0.6200, 0.0016, 0.8098],
        [0.3183, 0.2819, 0.9481]])

In [9]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [10]:
mat_b = torch.rand_like(mat_a, device = "cuda")

In [11]:
mat_b

tensor([[0.2194, 0.7777, 0.7079],
        [0.2219, 0.3231, 0.3370]], device='cuda:0')

In [12]:
mat_c = torch.rand_like(mat_b, device = "cpu")

In [13]:
mat_c

tensor([[0.1626, 0.0870, 0.9341],
        [0.4570, 0.4925, 0.8446]])

In [14]:
test_mat = torch.randint_like(x_zeros, low=0, high=10)

In [15]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

In [16]:
torch.linspace(start=-10, end=10, steps=1)

tensor([-10.])

In [17]:
torch.linspace(start=-10, end=10, steps=10)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

In [18]:
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [19]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [20]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
# pytorch allows broadcasting
# torch.add()
# torch.matmul() -> matrix multiplication
# torch.mul() -> element wise multiplication

In [22]:
mat_a.t()  # transpose

tensor([[1., 2.],
        [4., 7.],
        [5., 9.]])

In [23]:
# torch.squeeze(dim)

In [24]:
#torch.unsqueeze(x, 0)

In [25]:
torch.__version__

'2.9.1+cu126'

# Pytorch Autograd Use Case

In [26]:
dummy_var = torch.tensor(3.0, requires_grad =True)

In [27]:
print(dummy_var)

tensor(3., requires_grad=True)


In [28]:
function = dummy_var ** 2 + ( 3 * dummy_var) - 2

In [29]:
function

tensor(16., grad_fn=<SubBackward0>)

In [30]:
function.backward()

In [31]:
dummy_var.grad

tensor(9.)

# Use of ArgMax and Dim =0,1

In [32]:
mat_a

tensor([[1., 4., 5.],
        [2., 7., 9.]])

In [33]:
mat_a.mean(dim=0)

tensor([1.5000, 5.5000, 7.0000])

In [34]:
mat_a.mean(dim=1)

tensor([3.3333, 6.0000])

In [35]:
# max indecies for a matrix

indecies_col = mat_a.argmax(dim = 0)
indecies_row = mat_a.argmax(dim=1)

In [36]:
print(f"max indecies for matrix_a columnwise: {indecies_col}")
print(f"max indecies for matrix_a row-wise: {indecies_row}")

max indecies for matrix_a columnwise: tensor([1, 1, 1])
max indecies for matrix_a row-wise: tensor([2, 2])


# torch.gather()

In [42]:
# using gather function we can fetch particular elements from each row(dim=1) or column(dim=0)

In [39]:
var_a = torch.rand((3,4))
var_a

tensor([[0.5000, 0.6812, 0.3164, 0.2166],
        [0.4286, 0.6449, 0.0768, 0.6470],
        [0.7965, 0.8326, 0.3982, 0.0300]])

In [40]:
indecies_to_fetch = torch.tensor([
    [2],[1],[3]
])

In [41]:
torch.gather(var_a,dim=1,index= indecies_to_fetch)

tensor([[0.3164],
        [0.6449],
        [0.0300]])

In [43]:
col_indecies = torch.tensor([
    [0],[1],[2],[2]
])

In [44]:
torch.gather(var_a, dim =0, index = col_indecies)

tensor([[0.5000],
        [0.4286],
        [0.7965],
        [0.7965]])