In [1]:
import torch
torch.__version__

'2.9.1+cu126'

# Playing with Unsqueeze Function

In [2]:
var_x = torch.rand(3)

var_x.shape

In [4]:
var_y = var_x.unsqueeze(0)

In [5]:
var_y.shape

torch.Size([1, 3])

In [6]:
var_y

tensor([[0.0623, 0.4807, 0.9880]])

In [7]:
var_x

tensor([0.0623, 0.4807, 0.9880])

In [8]:
var_z = var_x.unsqueeze(1)

In [9]:
var_z

tensor([[0.0623],
        [0.4807],
        [0.9880]])

In [10]:
var_z.shape

torch.Size([3, 1])

# Use of seeds for reproduceability

In [12]:
torch.manual_seed(42)

In [13]:
x = torch.rand(3)
print(x)
print(f"shape of the random array is {x.shape}")

tensor([0.8823, 0.9150, 0.3829])
shape of the random array is torch.Size([3])
